# Generated by Django 3.0.1 on 2020-02-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblAdmin',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblGaji',
            fields=[
                ('id_gaji', models.AutoField(primary_key=True, serialize=False)),
                ('gaji_kotor', models.IntegerField()),
                ('jumlah_lembur', models.IntegerField()),
                ('pajak', models.IntegerField()),
                ('total_tunjangan', models.IntegerField()),
                ('gaji_bersih', models.IntegerField()),
                ('bulan', models.CharField(max_length=100)),
                ('tahun', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_gaji',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblJabatan',
            fields=[
                ('id_jabatan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_jabatan', models.CharField(max_length=100)),
                ('jumlah_gaji_pokok', models.IntegerField()),
                ('upah_lembur', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_jabatan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblKaryawan',
            fields=[
                ('id_karyawan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_karyawan', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('no_hp', models.IntegerField()),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('jenis_kelamin', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('jumlah_anak', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_karyawan',
                'managed': False,
            },
        ),
    ]
